# Setup
title:               Personal Blog
tagline:             Based on Lanyon
description:         Tech | Products | Apps
# url:                 
baseurl:             '/blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Adithya Krishna
  url:               https://www.linkedin.com/in/adithya-krishna-n-v-9a9b3b80/
  email:             nvadithyakrishna@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-169957818-1
